name: TestUI CI workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        java: ["17", "21", "23"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: "zulu"
      - name: Build with Maven
        run: mvn compile
#  TODO: Uncomment once all code is formatted
#  lint:
#    runs-on: ubuntu-latest
#    continue-on-error: true
#
#    steps:
#      - uses: actions/checkout@v3
#      - run: cat .github/super-linter.env >> "$GITHUB_ENV"
#      - name: Lint with Checkstyle
#        uses: github/super-linter@v4
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
